language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - nightly
sudo: false
install:
    - pip install coveralls
    - python setup.py build
script:
    - coverage run --source=mwparserfromhell setup.py -q test
after_success:
    - coveralls
env:
  matrix:
    - WITHOUT_EXTENSION=0
    - WITHOUT_EXTENSION=1
